version: "3.7"
services:
    nextjs:
        container_name: nextjs
        depends_on:
            - mysql
        build:
            context: ./
            dockerfile: ./Dockerfile/nextjs.dev
        volumes:
            - ./:/app
        ports:
            - "3000:3000"
        environment:
            - NEXT_PUBLIC_INFURA_KEY
            - DATABASE_URL

    nginx:
        container_name: nginx
        build:
            context: ./
            dockerfile: ./Dockerfile/nginx
        depends_on:
            - nextjs
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
        ports:
            - "80:80"

    mysql:
        container_name: mysql
        build:
            context: ./
            dockerfile: ./Dockerfile/mysql
        volumes:
            - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
            MYSQL_DATABASE: "${DATABASE_SCHEMA}"
            MYSQL_USER: "${DATABASE_USER}"
            MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
